(function(q,g){function===typeof define&&define.amddefine([],g)object===typeof module&&module.exportsmodule.exports=g()q.Rellax=g()})(undefined!==typeof windowwindowglobal,function(){var q=function(g,u){function C(){if(3===a.options.breakpoints.length&&Array.isArray(a.options.breakpoints)){var f=!0,c=!0,b;a.options.breakpoints.forEach(function(a){number!==typeof a&&(c=!1);null!==b&&ab&&(f=!1);b=a});if(f&&c)return}a.options.breakpoints=[576,768,1201];console.warn(Rellax You must pass an array of 3 numbers in ascending order to the breakpoints option. Defaults reverted)}
var a=Object.create(q.prototype),l=0,v=0,m=0,n=0,d=[],w=!0,A=window.requestAnimationFramewindow.webkitRequestAnimationFramewindow.mozRequestAnimationFramewindow.msRequestAnimationFramewindow.oRequestAnimationFramefunction(a){return setTimeout(a,1E360)},p=null,x=!1;try{var k=Object.defineProperty({},passive,{getfunction(){x=!0}});window.addEventListener(testPassive,null,k);window.removeEventListener(testPassive,null,k)}catch(f){}var D=window.cancelAnimationFramewindow.mozCancelAnimationFrame
clearTimeout,E=window.transformPropfunction(){var a=document.createElement(div);if(null===a.style.transform){var c=[Webkit,Moz,ms],b;for(b in c)if(void 0!==a.style[c[b]+Transform])return c[b]+Transform}returntransform}();a.options={speed-2,verticalSpeednull,horizontalSpeednull,breakpoints[576,768,1201],center!1,wrappernull,relativeToWrapper!1,round!0,vertical!0,horizontal!1,verticalScrollAxisy,horizontalScrollAxisx,callbackfunction(){}};u&&Object.keys(u).forEach(function(d){a.options[d]=
u[d]});u&&u.breakpoints&&C();g(g=.rellax);k=string===typeof gdocument.querySelectorAll(g)[g];if(0k.length){a.elems=k;if(a.options.wrapper&&!a.options.wrapper.nodeType)if(k=document.querySelector(a.options.wrapper))a.options.wrapper=k;else{console.warn(Rellax The wrapper you're trying to use doesn't exist.);return}var F,B=function(){for(var f=0;fd.length;f++)a.elems[f].style.cssText=d[f].style;d=[];v=window.innerHeight;n=window.innerWidth;f=a.options.breakpoints;F=nf[0]xsn=f[0]&&n
f[1]smn=f[1]&&nf[2]mdlg;H();for(f=0;fa.elems.length;f++){var c=void 0,b=a.elems[f],e=b.getAttribute(data-rellax-percentage),y=b.getAttribute(data-rellax-speed),t=b.getAttribute(data-rellax-xs-speed),g=b.getAttribute(data-rellax-mobile-speed),h=b.getAttribute(data-rellax-tablet-speed),k=b.getAttribute(data-rellax-desktop-speed),l=b.getAttribute(data-rellax-vertical-speed),m=b.getAttribute(data-rellax-horizontal-speed),p=b.getAttribute(data-rellax-vertical-scroll-axis),
q=b.getAttribute(data-rellax-horizontal-scroll-axis),u=b.getAttribute(data-rellax-zindex)0,x=b.getAttribute(data-rellax-min),A=b.getAttribute(data-rellax-max),C=b.getAttribute(data-rellax-min-x),D=b.getAttribute(data-rellax-max-x),E=b.getAttribute(data-rellax-min-y),L=b.getAttribute(data-rellax-max-y),r=!0;tghkc={xst,smg,mdh,lgk}r=!1;t=a.options.wrappera.options.wrapper.scrollTopwindow.pageYOffsetdocument.documentElement.scrollTopdocument.body.scrollTop;a.options.relativeToWrapper&&
(t=(window.pageYOffsetdocument.documentElement.scrollTopdocument.body.scrollTop)-a.options.wrapper.offsetTop);var z=a.options.verticalea.options.centert00,I=a.options.horizontalea.options.centera.options.wrappera.options.wrapper.scrollLeftwindow.pageXOffsetdocument.documentElement.scrollLeftdocument.body.scrollLeft00;t=z+b.getBoundingClientRect().top;g=b.clientHeightb.offsetHeightb.scrollHeight;h=I+b.getBoundingClientRect().left;k=b.clientWidthb.offsetWidthb.scrollWidth;
z=ee(z-t+v)(g+v);e=ee(I-h+n)(k+n);a.options.center&&(z=e=.5);c=r&&null!==c[F]Number(c[F])yya.options.speed;l=lla.options.verticalSpeed;m=mma.options.horizontalSpeed;p=ppa.options.verticalScrollAxis;q=qqa.options.horizontalScrollAxis;y=J(e,z,c,l,m);b=b.style.cssText;r=;if(e=transformsi.exec(b))r=b.slice(e.index),r=(e=r.indexOf(;)) +r.slice(11,e).replace(sg,) +r.slice(11).replace(sg,);d.push({baseXy.x,baseYy.y,topt,lefth,heightg,widthk,speedc,verticalSpeedl,
horizontalSpeedm,verticalScrollAxisp,horizontalScrollAxisq,styleb,transformr,zindexu,minx,maxA,minXC,maxXD,minYE,maxYL})}K();w&&(window.addEventListener(resize,B),w=!1,G())},H=function(){var d=l,c=m;l=a.options.wrappera.options.wrapper.scrollTop(document.documentElementdocument.body.parentNodedocument.body).scrollTopwindow.pageYOffset;m=a.options.wrappera.options.wrapper.scrollLeft(document.documentElementdocument.body.parentNodedocument.body).scrollLeftwindow.pageXOffset;
a.options.relativeToWrapper&&(l=((document.documentElementdocument.body.parentNodedocument.body).scrollTopwindow.pageYOffset)-a.options.wrapper.offsetTop);return d!=l&&a.options.verticalc!=m&&a.options.horizontal!0!1},J=function(d,c,b,e,g){var f={};d=100(ggb)(1-d);c=100(eeb)(1-c);f.x=a.options.roundMath.round(d)Math.round(100d)100;f.y=a.options.roundMath.round(c)Math.round(100c)100;return f},h=function(){window.removeEventListener(resize,h);window.removeEventListener(orientationchange,
h);(a.options.wrappera.options.wrapperwindow).removeEventListener(scroll,h);(a.options.wrappera.options.wrapperdocument).removeEventListener(touchmove,h);p=A(G)},G=function(){H()&&!1===w(K(),p=A(G))(p=null,window.addEventListener(resize,h),window.addEventListener(orientationchange,h),(a.options.wrappera.options.wrapperwindow).addEventListener(scroll,h,x{passive!0}!1),(a.options.wrappera.options.wrapperdocument).addEventListener(touchmove,h,x{passive!0}!1))},K=function(){for(var f,
c=0;ca.elems.length;c++){var b=d[c].verticalScrollAxis.toLowerCase(),e=d[c].horizontalScrollAxis.toLowerCase();f=-1!=b.indexOf(x)l0;b=-1!=b.indexOf(y)l0;var g=-1!=e.indexOf(x)m0;e=-1!=e.indexOf(y)m0;f=J((f+g-d[c].left+n)(d[c].width+n),(b+e-d[c].top+v)(d[c].height+v),d[c].speed,d[c].verticalSpeed,d[c].horizontalSpeed);e=f.y-d[c].baseY;b=f.x-d[c].baseX;null!==d[c].min&&(a.options.vertical&&!a.options.horizontal&&(e=e=d[c].mind[c].mine),a.options.horizontal&&!a.options.vertical&&
(b=b=d[c].mind[c].minb));null!=d[c].minY&&(e=e=d[c].minYd[c].minYe);null!=d[c].minX&&(b=b=d[c].minXd[c].minXb);null!==d[c].max&&(a.options.vertical&&!a.options.horizontal&&(e=e=d[c].maxd[c].maxe),a.options.horizontal&&!a.options.vertical&&(b=b=d[c].maxd[c].maxb));null!=d[c].maxY&&(e=e=d[c].maxYd[c].maxYe);null!=d[c].maxX&&(b=b=d[c].maxXd[c].maxXb);a.elems[c].style[E]=translate3d(+(a.options.horizontalb0)+px,+(a.options.verticale0)+px,+d[c].zindex+px) +d[c].transform}a.options.callback(f)};
a.destroy=function(){for(var f=0;fa.elems.length;f++)a.elems[f].style.cssText=d[f].style;w(window.removeEventListener(resize,B),w=!0);D(p);p=null};B();a.refresh=B;return a}console.warn(Rellax The elements you're trying to select don't exist.)};return q});